general {
    no_fade_in = false
    grace = 0
    disable_loading_bar = true
}

# --- BACKGROUND (Seu Wallpaper com Blur) ---
background {
    monitor =
    # Caminho exato do seu wallpaper atual
    path = /home/julio/Imagens/Wallpapers/arch.png
    color = rgba(25, 20, 20, 1.0)

    # Efeito de vidro fosco (Blur)
    blur_passes = 2
    blur_size = 7
    noise = 0.0117
    contrast = 0.8916
    brightness = 0.8172
    vibrancy = 0.1696
    vibrancy_darkness = 0.0
}

# --- INPUT FIELD (Campo de Senha) ---
input-field {
    monitor =
    size = 250, 50
    outline_thickness = 3
    dots_size = 0.33
    dots_spacing = 0.15
    dots_center = true
    
    # Cores Catppuccin Mocha
    outer_color = rgb(203, 166, 247) # Mauve (Roxo)
    inner_color = rgb(30, 30, 46)    # Base (Escuro)
    font_color = rgb(205, 214, 244)  # Texto (Branco)
    check_color = rgb(137, 180, 250) # Azul ao verificar
    fail_color = rgb(243, 139, 168)  # Vermelho se errar
    
    fade_on_empty = false
    font_family = JetBrainsMono Nerd Font
    placeholder_text = <i>Senha...</i>
    hide_input = false
    
    position = 0, -80
    halign = center
    valign = center
}

# --- RELÓGIO (Hora Grande) ---
label {
    monitor =
    text = cmd[update:1000] echo "$(date +"%H:%M")"
    color = rgba(205, 214, 244, 1.0)
    font_size = 100
    font_family = JetBrainsMono Nerd Font ExtraBold
    
    position = 0, 100
    halign = center
    valign = center
}

# --- DATA (Dia) ---
label {
    monitor =
    text = cmd[update:1000] echo "$(date +"%A, %d de %B")"
    color = rgba(205, 214, 244, 1.0)
    font_size = 20
    font_family = JetBrainsMono Nerd Font Bold
    
    position = 0, 20
    halign = center
    valign = center
}
